services:
  gost-proxy:
    image: gogost/gost:latest
    container_name: proxy
    restart: unless-stopped
    
    command: -L=proxy:20072007@:9000
    ports:
      - "9000:9000"

  tg-mtproto:
    image: nineseconds/mtg:2
    container_name: mtg
    restart: unless-stopped
    volumes:
      - ./cfg/mtg.toml:/config.toml
    ports:
      - "2053:3128"