# Порт, на котором слушает DNS-сервер
bind [::]:53

# Очищаем кэш при переподключениях
cache-size 8192
prefetch-domain yes

# --- ГРУППЫ DNS-СЕРВЕРОВ ---

# 1. Быстрые российские DNS для рунета (группа ru-dns)
server 77.88.8.8 -group ru-dns
server 77.88.8.1 -group ru-dns

# 2. Безопасные зашифрованные DoH
server-https https://dns.cloudflare.com/dns-query
server-https https://dns.google/dns-query


# --- МАРШРУТИЗАЦИЯ ---

domain-set -name blocked-list -type list -file /etc/smartdns/blocked-domains.txt
address /domain-set:blocked-list/__OUTER_SIDE_IP__

# Все российские домены на Яндекс.DNS
nameserver /ru/ru-dns
nameserver /su/ru-dns
nameserver /xn--p1ai/ru-dns