services:
  gost-proxy:
    image: gogost/gost:latest
    container_name: proxy
    restart: unless-stopped
    
    command: -L=${PROXY_LOGIN}:${PROXY_PASSWORD}@:9000
    ports:
      - "9000:9000"

  xray:
    image: ghcr.io/xtls/xray-core:latest
    container_name: xray
    restart: unless-stopped
    ports:
      - "9010:9010"
    volumes:
      - ./cfg/xray.json:/etc/xray/config.json:ro
    command: ["run", "-config", "/etc/xray/config.json"]

  gost-tg-receiver:
    image: gogost/gost:latest
    container_name: gost-receiver
    restart: unless-stopped
    # Принимаем шифрованный shadowsocks-туннель на порту 9000 и пересылаем локально на telemt:9020
    command: -L=ss://chacha20-ietf-poly1305:${GOST_PASSWORD}@:9020 -F=tcp://telemt:9030
    ports:
      - "9020:9020"

  telemt:
    image: ghcr.io/telemt/telemt:latest
    container_name: telemt
    restart: unless-stopped

    ports:
      - "9030:9030"

    working_dir: /etc/telemt
    volumes:
      - ./cfg/telemt.toml:/etc/telemt/config.toml:ro
    tmpfs:
      - /etc/telemt:rw,mode=1777,size=4m
    environment:
      - RUST_LOG=info

    healthcheck:
      test: [ "CMD", "/app/telemt", "healthcheck", "/etc/telemt/config.toml", "--mode", "liveness" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s

    cap_drop:
      - ALL

    cap_add:
      - NET_BIND_SERVICE

    read_only: true

    security_opt:
      - no-new-privileges:true

    ulimits:
      nofile:
        soft: 65536
        hard: 262144

    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "5"